spring.application.name=plExplorer
spring.profiles.active=dev


# Hibernate NE upravlja shemom - to radi Liquibase
spring.jpa.hibernate.ddl-auto=none

# Liquibase je zaduzen za migracije
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

